'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SideBar from './_components/SideBar';
import Contexts from './_contexts';
import { colors } from './_utils/colors';
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const pathname = usePathname();
    if (pathname === '/signin' || pathname === '/signup') {
        return (
            <html lang="en">
                <body className={inter.className} style={{ backgroundColor: colors.background }}>
                    <Contexts>{children}</Contexts>
                </body>
            </html>
        );
    }
    return (
        <html lang="en">
            <body className={inter.className} style={{ backgroundColor: colors.background }}>
                <Contexts>
                    <SideBar>{children}</SideBar>
                </Contexts>
            </body>
        </html>
    );
}
